- name: Enable swift Storage
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
  - openstack-swift-account
  - openstack-swift-account-replicator
  - openstack-swift-account-auditor
  - openstack-swift-account-reaper
  - openstack-swift-container
  - openstack-swift-container-replicator
  - openstack-swift-container-updater
  - openstack-swift-container-auditor
  - openstack-swift-object
  - openstack-swift-object-replicator
  - openstack-swift-object-updater
  - openstack-swift-object-auditor
  - openstack-swift-object-reconstructor
  tags:
  - storage