  # Swift Ring

- name: copy ring to swift etc dir
  copy: src={{ring_path}}/{{item}} dest=/etc/swift/{{item}} owner=swift group=root mode=0644
  with_items:
    - account.ring.gz
    - container.ring.gz
    - object.ring.gz
    - object-1.ring.gz



