---
addusers:
  - name: swift
    comment: "Swift user"
    createhome: yes
    home: "{{ swift_data_dir }}"
    system: yes
    shell: /bin/nologin
    group: "{{ swift_group }}"

  - name: "{{ system_username }}"
    comment: "system user"
    createhome: yes
    home: "/home/{{ system_username }}"
    system: yes
    group: "root"
    password: "{{ system_userpass }}"
