---

#
# Copyright (c) 2015 Davide Guerri <davide.guerri@gmail.com>
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: Configure keystone
  ini_file:
    dest: '/etc/keystone/keystone.conf'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  notify:
    - Restart webserver
  with_items:
    - section: 'DEFAULT'
      option: 'debug'
      value: '{{ openstack_keystone_verbose }}'
    - section: 'DEFAULT'
      option: 'admin_token'
      value: '{{ openstack_keystone_admin_token }}'
    - section: 'DEFAULT'
      option: 'log_dir'
      value: '{{ openstack_keystone_log_dir }}'
    - section: 'catalog'
      option: 'caching'
      value: '{{ openstack_keystone_catalog_caching|default(True) }}'
    - section: 'database'
      option: 'connection'
      value: '{{ openstack_keystone_database_url }}'
    - section: 'domain_config'
      option: 'caching'
      value: '{{ openstack_keystone_domain_config_caching|default(True) }}'
    - section: 'identity'
      option: 'caching'
      value: '{{ openstack_keystone_identity_caching|default(True) }}'
    - section: 'cache'
      option: 'memcache_servers'
      value: "{{ ','.join(openstack_keystone_memcached_servers) }}"
    - section: 'cache'
      option: 'enabled'
      value: "true"
    - section: 'cache'
      option: 'backend'
      value: "oslo_cache.memcache_pool"
    - section: 'cache'
      option: 'expiration_time'
      value: "600"
    - section: 'token'
      option: 'provider'
      value: 'fernet'
    - section: 'resource'
      option: 'caching'
      value: '{{ openstack_keystone_resource_caching|default(True) }}'
    - section: 'revoke'
      option: 'driver'
      value: 'sql'
    - section: 'revoke'
      option: 'caching'
      value: '{{ openstack_keystone_revoke_caching|default(True) }}'
    - section: 'role'
      option: 'caching'
      value: '{{ openstack_keystone_role_caching|default(True) }}'
    - section: 'token'
      option: 'caching'
      value: '{{ openstack_keystone_token_caching|default(True) }}'

- name: Render memcached conf
  template:
    src: memcached.jinja2
    dest: /etc/sysconfig/memcached
  notify:
    - Restart memcached
  tags:
  - keystone

- name: Get latest keystone database version
  shell: >-
    ls {{ openstack_keystone_database_migration_repository }}
    | grep '^[0-9]\{3\}_' | sort -n | tail -n 1 | awk -F '_' '{ print $1; }'
  changed_when: False
  register: openstack_keystone_database_schema_version

- name: Get current keystone database version
  command: 'keystone-manage db_version'
  run_once: True
  become: True
  become_user: 'keystone'
  changed_when: >-
    openstack_keystone_manage_db_version.stdout|int
    != openstack_keystone_database_schema_version.stdout|int
  register: openstack_keystone_manage_db_version
    
- name: Render bootstrap-keystone.sh
  run_once: true
  template:
    src: bootstrap-keystone.sh.jinja2
    dest: /tmp/bootstrap-keystone.sh
  tags:
  - keystone

- name: Bootstrap the Identity service
  run_once: true
  shell: bash /tmp/bootstrap-keystone.sh
  ignore_errors: yes
  tags:
  - keystone

- name: Copy the keystone keys to remote
  copy:
    src: "/etc/keystone/{{item}}-keys"
    dest: "/etc/keystone"
    owner: keystone
    group: keystone
  with_items:
    ["fernet", "credential"]
  # Configure the Apache HTTP server

- name: Config apache Listen
  shell: "sed -i 's/^Listen 8[01]/#Listen 80/g' /etc/httpd/conf/httpd.conf"
  notify:
    - Restart webserver
  tags:
  - keystone

- name: Remove apache 443 Listen
  shell: "sed -i 's/^Listen 443 https/#Listen 443 https/g' /etc/httpd/conf.d/ssl.conf"
  ignore_errors: true
  notify:
    - Restart webserver

- name: Fix keystone conf ownership
  file:
    group: 'keystone'
    owner: 'keystone'
    path: '/etc/keystone/'
    recurse: True
  when: ansible_os_family == 'RedHat'

- name: Fix keystone log ownership
  file:
    group: 'keystone'
    owner: 'keystone'
    path: '/var/log/keystone/'
    recurse: True
  when: ansible_os_family == 'RedHat'