- name: Config keystone mariadb script
  template:
    src: keystone.sql.jinja2
    dest: /tmp/keystone.sql
  tags:
  - mariadb

- name: Run keystone mariadb script
  shell: mysql -u root < /tmp/keystone.sql
  retries: 3
  delay: 60
  register: result
  until: result.rc == 0
  tags:
  - mariadb